### ISSUE TITLE
Firebase and GitHub OAuth Settings in Developer Applications

### ISSUE THREAD

**Issue by NicholasMurray** [AljoschaMeyer/react-firebase-social-logins#1]
Hi Aljoscha, 

Would it be possible for you to add redacted screen grabs of your Firebase and GitHub OAuth Developer applications settings for this app and add them to the Wiki.

I have tried to set mine up and changed the url in the componentWillMount example.js but it is failing and I am not sure why.

Regards,
Nicholas.

**Comment by AljoschaMeyer** [comment]
Can't make screenshots currently, but maybe this helps:

### Github:

`Application name: firebase social logins demo`
`Authorization callback URL: https://auth.firebase.com/v2/sociallogindemo/auth/github/callback`
- client id and client secret

### Firebase:

`Authorized Domains for OAuth Redirects: aljoschameyer.github.io`
`Enable Github Authentication: true`
- client id and client secret copypasted from github

I thing that should be all relevant settings, both on the github side and the firebase side.

**Comment by NicholasMurray** [comment]
Are you using the older version of Firebase? 

This is the entry in Firebase for me using the new Firebase Console

To complete setup, add this authorisation callback URL to your GitHub app configuration. 
https://pizzini-fa9b8.firebaseapp.com/__/auth/handler 

I am trying to run this locally.

**Comment by AljoschaMeyer** [comment]
Yes, this still uses the old version.

I think I can't really help you here. This was just some one-off project, I haven't done anything with Firebase since then. Your problems don't seem to be related to this project, but to Firebase and authentication in general. You might have better luck using whatever support channels Firebase offers.

**Comment by NicholasMurray** [comment]
Yes, will do, thanks for your help.
