### ISSUE TITLE
Demo no longer works

### ISSUE THREAD

**Issue by dandv** [AljoschaMeyer/react-firebase-social-logins#2]
No matter what button I click, I get this error:

> {"error":{"code":"PROJECT_REQUIRES_IMPORT","statusCode":428,"message":"This Firebase project requires import into Google Cloud Platform to resume service.","details":"Visit the docs (https://firebase.google.com/support/guides/firebase-web#import_your_project_to_the_firebase_console) or reach out to Firebase support (https://firebase.google.com/support/contact/account-services/) for help. Without action, this project will be permanently deleted on Tuesday, May 15th, 2018."}}

**Comment by AljoschaMeyer** [comment]
Thanks for the report. Unfortunately I abandoned this project quite a while ago. I [updated](https://github.com/AljoschaMeyer/react-firebase-social-logins/commit/4c3a972c908f1db900a4e0a2ec594e18f99044e0) the README accordingly.

Given your profile description, this is probably not the reaction you wanted, so sorry for that.
